export const actionTypes = {
  TOGGLE_THEME: "TOGGLE_THEME",
  GET_COUNTRIES: "GET_COUNTRIES",
  FILTER: "FILTER",
  REQUEST_SEND: "REQUEST_SEND",
  REQUEST_FAILURE: "REQUEST_FAILURE",
  MOVIE_DETAIL: "MOVIE_DETAIL",
  SEARCH_COUNTRIES: "SEARCH_COUNTRIES",
};
